name: run
gpu: 0
seed: 42
dev_run: false

# Data parameters
data:
  task: mortality
  fold: 1
  matched: true
  timestep: 1.0
  ehr_root: /research/miccai/datasets/mimiciv_multimodal_full/data
  resized_cxr_root: /research/mimic_cxr_resized
  image_meta_path: /hdd/datasets/mimic-cxr-jpg/2.0.0/mimic-cxr-2.0.0-metadata.csv
  pkl_dir: './data_pkls'

stage: "fuse"

# Model parameters
model:
  ehr_modal_distill: true
  cxr_modal_distill: true
  hidden_size: 256
  ehr_distill_loss_weight: 1
  cxr_distill_loss_weight: 1
  dropout: 0.2
  ada_loss_weight: true

  enable_mixing: true
  mixup_alpha: 0.2
  cutmix_alpha: 1.0
  mix_prob: 0.5
  lambda_min: 0.3
  grad_clip_val: 1.0

ehr_model:
  checkpoint_path:
    mortality: ./teacher_model_checkpoints/mortality_matched_fold1_ehr_0.61.ckpt
    phenotype: ./teacher_model_checkpoints/phenotype_matched_fold1_ehr_0.42.ckpt
  hidden_size: 256
  n_head: 4
  n_layers: 1
  dropout: 0.2
  criterion: "bce"

cxr_model:
  checkpoint_path: 
    mortality: ./teacher_model_checkpoints/mortality_matched_fold1_cxr_0.26.ckpt
    phenotype: ./teacher_model_checkpoints/phenotype_matched_fold1_cxr_0.39.ckpt
  hidden_size: 256  # retrain?
  dropout: 0.2

# Training parameters
training:
  num_workers: 4
  batch_size: 32
  num_epochs: 100
  patience: 10
  learning_rate: 0.0001
  weight_decay: 0

